apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api-configmap.yaml
  - api-secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - web-nginx-configmap.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
